services:
  nginx:
    image: nginx:latest
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      # - ./www:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - 8080:80
    networks:
      - app
  "php-fpm":
    image: "php:8.2-fpm"
    volumes:
      - ./php-fpm/conf.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./www:/var/www/html
    # ports:
    #  - 9000:9000
    scale: 3
    networks:
      - app

networks:
  app: