apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-sandbox
spec:
  selector:
    matchLabels:
      app: php-fpm-sandbox
  template:
    metadata:
      labels:
        app: php-fpm-sandbox
    spec:
      containers:
      - name: php-fpm-sandbox
        image: ghcr.io/xputerax/php-fpm-sandbox:chore-pipelines-9d646bd
        resources:
          limits:
            memory: "128Mi"
            cpu: "128m"
        ports:
        - containerPort: 80