apiVersion: v1
kind: Service
metadata:
  name: php-fpm-sandbox-separate-svc
spec:
  selector:
    app: php-fpm-sandbox-separate
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: php-fpm-sandbox-separate-ingress
  labels:
    app.kubernetes.io/name: php-fpm-sandbox-separate-ingress
    app: php-fpm-sandbox-separate
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: rke.lab.aimandaniel.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/sandbox-separate/(.+)$"
        backend:
          service:
            name: php-fpm-sandbox-separate-svc
            port:
              number: 80
