apiVersion: v1
kind: Service
metadata:
  name: php-fpm-sandbox-svc
spec:
  selector:
    app: php-fpm-sandbox
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: php-fpm-sandbox-ingress
  labels:
    app.kubernetes.io/name: php-fpm-sandbox-ingress
    app: php-fpm-sandbox
spec:
  rules:
  - host: rke.lab.aimandaniel.com
    http:
      paths:
      - pathType: Prefix
        path: "/sandbox"
        backend:
          service:
            name: php-fpm-sandbox-svc
            port:
              number: 80
